[build]
  command = """
    python3 -m pip install --upgrade pip &&
    python3 -m pip install -r requirements.txt &&
    mkdir -p dist
  """
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[build.processing]
  skip_processing = true
