[build]
  command = """
    pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 