[build]
  command = """
    python -V &&
    pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 