[build]
  command = """
    python3 -m pip install --upgrade pip &&
    python3 -m pip install -r requirements.txt
  """
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  external_node_modules = ["flask-lambda"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200