[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200